export const GET_TOP_ARTISTS_REQUEST: 'GET_TOP_ARTISTS_REQUEST' = 'GET_TOP_ARTISTS_REQUEST';
export const GET_TOP_ARTISTS_FAILED: 'GET_TOP_ARTISTS_FAILED' = 'GET_TOP_ARTISTS_FAILED';
export const GET_TOP_ARTISTS_SUCCESS: 'GET_TOP_ARTISTS_SUCCESS' = 'GET_TOP_ARTISTS_SUCCESS';