export const GET_GENRES_COUNTRY_REQUEST: 'GET_GENRES_COUNTRY_REQUEST' = 'GET_GENRES_COUNTRY_REQUEST';
export const GET_GENRES_COUNTRY_FAILED: 'GET_GENRES_COUNTRY_FAILED' = 'GET_GENRES_COUNTRY_FAILED';
export const GET_GENRES_COUNTRY_SUCCESS: 'GET_GENRES_COUNTRY_SUCCESS' = 'GET_GENRES_COUNTRY_SUCCESS';