export const GET_CHART_LIST_REQUEST: 'GET_CHART_LIST_REQUEST' = 'GET_CHART_LIST_REQUEST';
export const GET_CHART_LIST_FAILED: 'GET_CHART_LIST_FAILED' = 'GET_CHART_LIST_FAILED';
export const GET_CHART_LIST_SUCCESS: 'GET_CHART_LIST_SUCCESS' = 'GET_CHART_LIST_SUCCESS';

export const GET_GENRES_COUNTRY_REQUEST: 'GET_GENRES_COUNTRY_REQUEST' = 'GET_GENRES_COUNTRY_REQUEST';
export const GET_GENRES_COUNTRY_FAILED: 'GET_GENRES_COUNTRY_FAILED' = 'GET_GENRES_COUNTRY_FAILED';
export const GET_GENRES_COUNTRY_SUCCESS: 'GET_GENRES_COUNTRY_SUCCESS' = 'GET_GENRES_COUNTRY_SUCCESS';

export const GET_GENRE_TRACKS_REQUEST: 'GET_GENRE_TRACKS_REQUEST' = 'GET_GENRE_TRACKS_REQUEST';
export const GET_GENRE_TRACKS_FAILED: 'GET_GENRE_TRACKS_FAILED' = 'GET_GENRE_TRACKS_FAILED';
export const GET_GENRE_TRACKS_SUCCESS: 'GET_GENRE_TRACKS_SUCCESS' = 'GET_GENRE_TRACKS_SUCCESS';

export const ADD_TO_PLAYER: 'ADD_TO_PLAYER' = 'ADD_TO_PLAYER';

export const ACTIVE_PLAYER: 'ACTIVE_PLAYER' = 'ACTIVE_PLAYER';
export const INACTIVE_PLAYER: 'INACTIVE_PLAYER' = 'INACTIVE_PLAYER';

export const NEXT_TRACK: 'NEXT_TRACK' = 'NEXT_TRACK';
export const PREV_TRACK: 'PREV_TRACK' = 'PREV_TRACK';