export const ADD_TO_PLAYER: 'ADD_TO_PLAYER' = 'ADD_TO_PLAYER';
export const PLAY_PAUSE: 'PLAY_PAUSE' = 'PLAY_PAUSE';

export const ACTIVE_PLAYER: 'ACTIVE_PLAYER' = 'ACTIVE_PLAYER';
export const INACTIVE_PLAYER: 'INACTIVE_PLAYER' = 'INACTIVE_PLAYER';

export const NEXT_TRACK: 'NEXT_TRACK' = 'NEXT_TRACK';
export const PREV_TRACK: 'PREV_TRACK' = 'PREV_TRACK';